Exit when an error found

diff --git a/Scripts/boot-simulator b/Scripts/boot-simulator
--- a/Scripts/boot-simulator
+++ b/Scripts/boot-simulator
@@ -37,13 +37,10 @@ do
             ;;
     esac
 done
-if [ -z "$identifier" ]; then
-    echo 'error: too few arguments.' >&2
+if [ -z "$identifier" -o $# -ne 0 ]; then
+    echo 'error: wrong number of arguments.' >&2
     show_help >&2
-fi
-if [ $# -ne 0 ]; then
-    echo 'error: too many arguments.' >&2
-    show_help >&2
+    exit 1
 fi
 
 if [ $destination -ne 0 ]; then
